title: "Sung Hee Park"
description: "Postdoctoral Researcher | Biostatistics & Data Science"
baseurl: ""
url: "https://sparkqkr.github.io"
markdown: kramdown
theme: null

collections:
  papers:
    output: true
    permalink: /papers/:name/
