title: "Sung Hee Park"
description: "Postdoctoral Researcher | Biostatistics & Data Science"
baseurl: ""
url: "https://sparkqkr.github.io"
markdown: kramdown
theme: null

collections:
  papers:
    output: true
    permalink: /papers/:name/

defaults:
  - scope:
      path: ""
      type: papers
    values:
      layout: paper   # use the paper layout we’ll create next
